create table public.fonts (
  id bigint generated by default as identity primary key,
  family text not null unique,
  url text not null,
  category text not null check (category in ('display', 'serif', 'sans-serif', 'monospace', 'handwriting')),
  num_liked integer not null default 0 check (num_liked >= 0)
);

create table public.font_pairings (
  id bigint generated by default as identity primary key,
  font_title_id bigint not null references public.fonts (id) on delete cascade,
  font_content_id bigint not null references public.fonts (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  num_views integer not null default 0 check (num_views >= 0),
  num_liked integer not null default 0 check (num_liked >= 0),
  unique (font_title_id, font_content_id)
);

create index font_pairings_created_at_idx
  on public.font_pairings (created_at desc);

create index font_pairings_num_liked_idx
  on public.font_pairings (num_liked desc);

create index font_pairings_title_font_id_idx
  on public.font_pairings (font_title_id);

create index font_pairings_content_font_id_idx
  on public.font_pairings (font_content_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger font_pairings_set_updated_at
before update on public.font_pairings
for each row
execute function public.set_updated_at();

alter table public.fonts enable row level security;
alter table public.font_pairings enable row level security;

grant select on public.fonts to anon, authenticated;
grant select on public.font_pairings to anon, authenticated;

grant usage on schema public to anon, authenticated;

create policy "Anyone can read fonts"
on public.fonts
for select
to anon, authenticated
using (true);

create policy "Anyone can read font pairings"
on public.font_pairings
for select
to anon, authenticated
using (true);

create or replace function public.record_pairing_view(
  p_font_title_id bigint,
  p_font_content_id bigint
)
returns public.font_pairings
language plpgsql
security definer
set search_path = public
as $$
declare
  pairing public.font_pairings;
begin
  insert into public.font_pairings (font_title_id, font_content_id, num_views)
  values (p_font_title_id, p_font_content_id, 1)
  on conflict (font_title_id, font_content_id)
  do update set num_views = public.font_pairings.num_views + 1
  returning * into pairing;

  return pairing;
end;
$$;

create or replace function public.record_pairing_like(
  p_font_title_id bigint,
  p_font_content_id bigint
)
returns public.font_pairings
language plpgsql
security definer
set search_path = public
as $$
declare
  pairing public.font_pairings;
begin
  insert into public.font_pairings (font_title_id, font_content_id, num_liked)
  values (p_font_title_id, p_font_content_id, 1)
  on conflict (font_title_id, font_content_id)
  do update set num_liked = public.font_pairings.num_liked + 1
  returning * into pairing;

  update public.fonts
  set num_liked = num_liked + 1
  where id in (p_font_title_id, p_font_content_id);

  return pairing;
end;
$$;

revoke all on function public.record_pairing_view(bigint, bigint) from public;
revoke all on function public.record_pairing_like(bigint, bigint) from public;
grant execute on function public.record_pairing_view(bigint, bigint) to anon, authenticated;
grant execute on function public.record_pairing_like(bigint, bigint) to anon, authenticated;
